CREATE TABLE `subject_information` (
    `subject_information_pk` varchar(23) COLLATE utf8mb4_unicode_ci NOT NULL,
    `subject_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `subject_number` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `subject_year` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `subject_semester` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `subject_name` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
    `professor_id` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `created_college` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `governed_college` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
    `lecture_credit` int NOT NULL,
    `lecture_type` enum('교선', '교필', '전선', '전필', '일선', '기필') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `lecture_max_personnel` tinyint DEFAULT NULL,
    `lecture_applied_number` tinyint DEFAULT NULL,
    `lecture_exclusive` enum('Y', 'N') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y',
    `university_exclusive` enum('Y', 'N') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y',
    `lecture_building` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `lecture_room_number` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `others` text COLLATE utf8mb4_unicode_ci,
    `lecture_bound` enum('1영역', '2영역', '3영역') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `special_course` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `dad_of_revenge` enum('Y', 'N') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    PRIMARY KEY (`subject_information_pk`),
    KEY `fk_professor_id` (`professor_id`),
    KEY `fk_created_college` (`created_college`),
    KEY `fk_governed_college` (`governed_college`),
    CONSTRAINT `subject_information_ibfk_1` FOREIGN KEY (`professor_id`) REFERENCES `professor_information` (`professor_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `subject_information_ibfk_2` FOREIGN KEY (`created_college`) REFERENCES `major_information` (`major_code`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `subject_information_ibfk_3` FOREIGN KEY (`governed_college`) REFERENCES `major_information` (`major_code`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci